FROM node:22-alpine

RUN apk add --no-cache unzip

RUN npm install -g pnpm --fetch-retry-mintimeout 20000 --fetch-retry-maxtimeout 120000 || corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml* ./
RUN pnpm install

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev"]
